//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1873.
// 
#pragma warning disable 1591

namespace AirSoft.FlightMonitor.FlightMonitorBF.PublicService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PublicServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PublicService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAirportInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAirportLocationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PublicService() {
            this.Url = global::AirSoft.FlightMonitor.FlightMonitorBF.Properties.Settings.Default.AirSoft_FlightMonitor_FlightMonitorBF_PublicService_PublicService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAirportInfoCompletedEventHandler GetAirportInfoCompleted;
        
        /// <remarks/>
        public event GetAirportLocationCompletedEventHandler GetAirportLocationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAirportInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAirportInfo(string airportFourCode, string airportThreeCode, string airportCnName, string airportEnName, string areaName, string isSelf) {
            object[] results = this.Invoke("GetAirportInfo", new object[] {
                        airportFourCode,
                        airportThreeCode,
                        airportCnName,
                        airportEnName,
                        areaName,
                        isSelf});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAirportInfoAsync(string airportFourCode, string airportThreeCode, string airportCnName, string airportEnName, string areaName, string isSelf) {
            this.GetAirportInfoAsync(airportFourCode, airportThreeCode, airportCnName, airportEnName, areaName, isSelf, null);
        }
        
        /// <remarks/>
        public void GetAirportInfoAsync(string airportFourCode, string airportThreeCode, string airportCnName, string airportEnName, string areaName, string isSelf, object userState) {
            if ((this.GetAirportInfoOperationCompleted == null)) {
                this.GetAirportInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAirportInfoOperationCompleted);
            }
            this.InvokeAsync("GetAirportInfo", new object[] {
                        airportFourCode,
                        airportThreeCode,
                        airportCnName,
                        airportEnName,
                        areaName,
                        isSelf}, this.GetAirportInfoOperationCompleted, userState);
        }
        
        private void OnGetAirportInfoOperationCompleted(object arg) {
            if ((this.GetAirportInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAirportInfoCompleted(this, new GetAirportInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAirportLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAirportLocation(string strAPCode) {
            object[] results = this.Invoke("GetAirportLocation", new object[] {
                        strAPCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAirportLocationAsync(string strAPCode) {
            this.GetAirportLocationAsync(strAPCode, null);
        }
        
        /// <remarks/>
        public void GetAirportLocationAsync(string strAPCode, object userState) {
            if ((this.GetAirportLocationOperationCompleted == null)) {
                this.GetAirportLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAirportLocationOperationCompleted);
            }
            this.InvokeAsync("GetAirportLocation", new object[] {
                        strAPCode}, this.GetAirportLocationOperationCompleted, userState);
        }
        
        private void OnGetAirportLocationOperationCompleted(object arg) {
            if ((this.GetAirportLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAirportLocationCompleted(this, new GetAirportLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetAirportInfoCompletedEventHandler(object sender, GetAirportInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAirportInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAirportInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetAirportLocationCompletedEventHandler(object sender, GetAirportLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAirportLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAirportLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591