//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3662
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3662.
// 
#pragma warning disable 1591

namespace AirSoft.FlightMonitor.FlightMonitorClient.PaxService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaxServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PaxService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PaxCheckConnectOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaxCheckDisConnectOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaxCheckNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaxCargoInforOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PaxService() {
            this.Url = global::AirSoft.FlightMonitor.FlightMonitorClient.Properties.Settings.Default.AirSoft_FlightMonitor_FlightMonitorClient_PaxService_PaxService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PaxCheckConnectCompletedEventHandler PaxCheckConnectCompleted;
        
        /// <remarks/>
        public event PaxCheckDisConnectCompletedEventHandler PaxCheckDisConnectCompleted;
        
        /// <remarks/>
        public event PaxCheckNumCompletedEventHandler PaxCheckNumCompleted;
        
        /// <remarks/>
        public event PaxCargoInforCompletedEventHandler PaxCargoInforCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaxCheckConnect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PaxCheckConnect() {
            object[] results = this.Invoke("PaxCheckConnect", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PaxCheckConnectAsync() {
            this.PaxCheckConnectAsync(null);
        }
        
        /// <remarks/>
        public void PaxCheckConnectAsync(object userState) {
            if ((this.PaxCheckConnectOperationCompleted == null)) {
                this.PaxCheckConnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaxCheckConnectOperationCompleted);
            }
            this.InvokeAsync("PaxCheckConnect", new object[0], this.PaxCheckConnectOperationCompleted, userState);
        }
        
        private void OnPaxCheckConnectOperationCompleted(object arg) {
            if ((this.PaxCheckConnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaxCheckConnectCompleted(this, new PaxCheckConnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaxCheckDisConnect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PaxCheckDisConnect() {
            this.Invoke("PaxCheckDisConnect", new object[0]);
        }
        
        /// <remarks/>
        public void PaxCheckDisConnectAsync() {
            this.PaxCheckDisConnectAsync(null);
        }
        
        /// <remarks/>
        public void PaxCheckDisConnectAsync(object userState) {
            if ((this.PaxCheckDisConnectOperationCompleted == null)) {
                this.PaxCheckDisConnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaxCheckDisConnectOperationCompleted);
            }
            this.InvokeAsync("PaxCheckDisConnect", new object[0], this.PaxCheckDisConnectOperationCompleted, userState);
        }
        
        private void OnPaxCheckDisConnectOperationCompleted(object arg) {
            if ((this.PaxCheckDisConnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaxCheckDisConnectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaxCheckNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PaxCheckNum(string strCommnadText, string UserName, string Password) {
            object[] results = this.Invoke("PaxCheckNum", new object[] {
                        strCommnadText,
                        UserName,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PaxCheckNumAsync(string strCommnadText, string UserName, string Password) {
            this.PaxCheckNumAsync(strCommnadText, UserName, Password, null);
        }
        
        /// <remarks/>
        public void PaxCheckNumAsync(string strCommnadText, string UserName, string Password, object userState) {
            if ((this.PaxCheckNumOperationCompleted == null)) {
                this.PaxCheckNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaxCheckNumOperationCompleted);
            }
            this.InvokeAsync("PaxCheckNum", new object[] {
                        strCommnadText,
                        UserName,
                        Password}, this.PaxCheckNumOperationCompleted, userState);
        }
        
        private void OnPaxCheckNumOperationCompleted(object arg) {
            if ((this.PaxCheckNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaxCheckNumCompleted(this, new PaxCheckNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaxCargoInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PaxCargoInfor(string strCommnadText, string UserName, string Password) {
            object[] results = this.Invoke("PaxCargoInfor", new object[] {
                        strCommnadText,
                        UserName,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PaxCargoInforAsync(string strCommnadText, string UserName, string Password) {
            this.PaxCargoInforAsync(strCommnadText, UserName, Password, null);
        }
        
        /// <remarks/>
        public void PaxCargoInforAsync(string strCommnadText, string UserName, string Password, object userState) {
            if ((this.PaxCargoInforOperationCompleted == null)) {
                this.PaxCargoInforOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaxCargoInforOperationCompleted);
            }
            this.InvokeAsync("PaxCargoInfor", new object[] {
                        strCommnadText,
                        UserName,
                        Password}, this.PaxCargoInforOperationCompleted, userState);
        }
        
        private void OnPaxCargoInforOperationCompleted(object arg) {
            if ((this.PaxCargoInforCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaxCargoInforCompleted(this, new PaxCargoInforCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PaxCheckConnectCompletedEventHandler(object sender, PaxCheckConnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaxCheckConnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaxCheckConnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PaxCheckDisConnectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PaxCheckNumCompletedEventHandler(object sender, PaxCheckNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaxCheckNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaxCheckNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PaxCargoInforCompletedEventHandler(object sender, PaxCargoInforCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaxCargoInforCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaxCargoInforCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591