//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1873.
// 
#pragma warning disable 1591

namespace AirSoft.FlightMonitor.FlightMonitorBF.CFPWPService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="clsWebServiceOfFPLInfoSoap", Namespace="http://tempuri.org/")]
    public partial class clsWebServiceOfFPLInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReturnWayPointsOfFPLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnInfoOfFPLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public clsWebServiceOfFPLInfo() {
            this.Url = global::AirSoft.FlightMonitor.FlightMonitorBF.Properties.Settings.Default.AirSoft_FlightMonitor_FlightMonitorBF_CFPWPService_clsWebServiceOfFPLInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReturnWayPointsOfFPLCompletedEventHandler ReturnWayPointsOfFPLCompleted;
        
        /// <remarks/>
        public event ReturnInfoOfFPLCompletedEventHandler ReturnInfoOfFPLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnWayPointsOfFPL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReturnWayPointsOfFPL(System.DateTime dtPDateOfFlight, string strPFlightNO, string strPPlaneNO, string strPDepSTN, string strPArrSTN, string strPTableName) {
            object[] results = this.Invoke("ReturnWayPointsOfFPL", new object[] {
                        dtPDateOfFlight,
                        strPFlightNO,
                        strPPlaneNO,
                        strPDepSTN,
                        strPArrSTN,
                        strPTableName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnWayPointsOfFPLAsync(System.DateTime dtPDateOfFlight, string strPFlightNO, string strPPlaneNO, string strPDepSTN, string strPArrSTN, string strPTableName) {
            this.ReturnWayPointsOfFPLAsync(dtPDateOfFlight, strPFlightNO, strPPlaneNO, strPDepSTN, strPArrSTN, strPTableName, null);
        }
        
        /// <remarks/>
        public void ReturnWayPointsOfFPLAsync(System.DateTime dtPDateOfFlight, string strPFlightNO, string strPPlaneNO, string strPDepSTN, string strPArrSTN, string strPTableName, object userState) {
            if ((this.ReturnWayPointsOfFPLOperationCompleted == null)) {
                this.ReturnWayPointsOfFPLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnWayPointsOfFPLOperationCompleted);
            }
            this.InvokeAsync("ReturnWayPointsOfFPL", new object[] {
                        dtPDateOfFlight,
                        strPFlightNO,
                        strPPlaneNO,
                        strPDepSTN,
                        strPArrSTN,
                        strPTableName}, this.ReturnWayPointsOfFPLOperationCompleted, userState);
        }
        
        private void OnReturnWayPointsOfFPLOperationCompleted(object arg) {
            if ((this.ReturnWayPointsOfFPLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnWayPointsOfFPLCompleted(this, new ReturnWayPointsOfFPLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnInfoOfFPL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReturnInfoOfFPL(System.DateTime dtPDateOfFlight, string strPFlightNO, string strPPlaneNO, string strPDepSTN, string strPArrSTN) {
            object[] results = this.Invoke("ReturnInfoOfFPL", new object[] {
                        dtPDateOfFlight,
                        strPFlightNO,
                        strPPlaneNO,
                        strPDepSTN,
                        strPArrSTN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnInfoOfFPLAsync(System.DateTime dtPDateOfFlight, string strPFlightNO, string strPPlaneNO, string strPDepSTN, string strPArrSTN) {
            this.ReturnInfoOfFPLAsync(dtPDateOfFlight, strPFlightNO, strPPlaneNO, strPDepSTN, strPArrSTN, null);
        }
        
        /// <remarks/>
        public void ReturnInfoOfFPLAsync(System.DateTime dtPDateOfFlight, string strPFlightNO, string strPPlaneNO, string strPDepSTN, string strPArrSTN, object userState) {
            if ((this.ReturnInfoOfFPLOperationCompleted == null)) {
                this.ReturnInfoOfFPLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnInfoOfFPLOperationCompleted);
            }
            this.InvokeAsync("ReturnInfoOfFPL", new object[] {
                        dtPDateOfFlight,
                        strPFlightNO,
                        strPPlaneNO,
                        strPDepSTN,
                        strPArrSTN}, this.ReturnInfoOfFPLOperationCompleted, userState);
        }
        
        private void OnReturnInfoOfFPLOperationCompleted(object arg) {
            if ((this.ReturnInfoOfFPLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnInfoOfFPLCompleted(this, new ReturnInfoOfFPLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ReturnWayPointsOfFPLCompletedEventHandler(object sender, ReturnWayPointsOfFPLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnWayPointsOfFPLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnWayPointsOfFPLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ReturnInfoOfFPLCompletedEventHandler(object sender, ReturnInfoOfFPLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnInfoOfFPLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnInfoOfFPLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591