//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3649
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSoft.FlightMonitor.FlightMonitorBF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.104.4/net/Webservice/InfoOfFPL.asmx")]
        public string AirSoft_FlightMonitor_FlightMonitorBF_CFPWPService_clsWebServiceOfFPLInfo {
            get {
                return ((string)(this["AirSoft_FlightMonitor_FlightMonitorBF_CFPWPService_clsWebServiceOfFPLInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.104.5/publicservice/publicservice.asmx")]
        public string AirSoft_FlightMonitor_FlightMonitorBF_PublicService_PublicService {
            get {
                return ((string)(this["AirSoft_FlightMonitor_FlightMonitorBF_PublicService_PublicService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.58.163/SimWebService/Service.asmx")]
        public string AirSoft_FlightMonitor_FlightMonitorBF_SimWebService_Service {
            get {
                return ((string)(this["AirSoft_FlightMonitor_FlightMonitorBF_SimWebService_Service"]));
            }
        }
    }
}
