//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3662
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3662.
// 
#pragma warning disable 1591

namespace MessageService.OMPWebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FlightMonitorDataSoap", Namespace="http://tempuri.org/")]
    public partial class FlightMonitorData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataItemPurviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaintainGuaranteeInforOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGuaranteeInforOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGuaranteeRecordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FlightMonitorData() {
            this.Url = global::MessageService.Properties.Settings.Default.MessageService_OMPWebReference_FlightMonitorData;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataItemPurviewCompletedEventHandler GetDataItemPurviewCompleted;
        
        /// <remarks/>
        public event MaintainGuaranteeInforCompletedEventHandler MaintainGuaranteeInforCompleted;
        
        /// <remarks/>
        public event GetGuaranteeInforCompletedEventHandler GetGuaranteeInforCompleted;
        
        /// <remarks/>
        public event AddGuaranteeRecordCompletedEventHandler AddGuaranteeRecordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataItemPurview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDataItemPurview(string UserID) {
            object[] results = this.Invoke("GetDataItemPurview", new object[] {
                        UserID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataItemPurviewAsync(string UserID) {
            this.GetDataItemPurviewAsync(UserID, null);
        }
        
        /// <remarks/>
        public void GetDataItemPurviewAsync(string UserID, object userState) {
            if ((this.GetDataItemPurviewOperationCompleted == null)) {
                this.GetDataItemPurviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataItemPurviewOperationCompleted);
            }
            this.InvokeAsync("GetDataItemPurview", new object[] {
                        UserID}, this.GetDataItemPurviewOperationCompleted, userState);
        }
        
        private void OnGetDataItemPurviewOperationCompleted(object arg) {
            if ((this.GetDataItemPurviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataItemPurviewCompleted(this, new GetDataItemPurviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MaintainGuaranteeInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MaintainGuaranteeInfor(
                    string UserID, 
                    string FLTID, 
                    string DATOP, 
                    int LegNo, 
                    string AC, 
                    string DepSTN, 
                    string ArrSTN, 
                    string STD, 
                    string ETD, 
                    string STA, 
                    string ETA, 
                    string ChangeReasonCode, 
                    string ChangeOldContent, 
                    string ChangeNewContent, 
                    int FieldType, 
                    string LocalOperatingTime) {
            object[] results = this.Invoke("MaintainGuaranteeInfor", new object[] {
                        UserID,
                        FLTID,
                        DATOP,
                        LegNo,
                        AC,
                        DepSTN,
                        ArrSTN,
                        STD,
                        ETD,
                        STA,
                        ETA,
                        ChangeReasonCode,
                        ChangeOldContent,
                        ChangeNewContent,
                        FieldType,
                        LocalOperatingTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MaintainGuaranteeInforAsync(
                    string UserID, 
                    string FLTID, 
                    string DATOP, 
                    int LegNo, 
                    string AC, 
                    string DepSTN, 
                    string ArrSTN, 
                    string STD, 
                    string ETD, 
                    string STA, 
                    string ETA, 
                    string ChangeReasonCode, 
                    string ChangeOldContent, 
                    string ChangeNewContent, 
                    int FieldType, 
                    string LocalOperatingTime) {
            this.MaintainGuaranteeInforAsync(UserID, FLTID, DATOP, LegNo, AC, DepSTN, ArrSTN, STD, ETD, STA, ETA, ChangeReasonCode, ChangeOldContent, ChangeNewContent, FieldType, LocalOperatingTime, null);
        }
        
        /// <remarks/>
        public void MaintainGuaranteeInforAsync(
                    string UserID, 
                    string FLTID, 
                    string DATOP, 
                    int LegNo, 
                    string AC, 
                    string DepSTN, 
                    string ArrSTN, 
                    string STD, 
                    string ETD, 
                    string STA, 
                    string ETA, 
                    string ChangeReasonCode, 
                    string ChangeOldContent, 
                    string ChangeNewContent, 
                    int FieldType, 
                    string LocalOperatingTime, 
                    object userState) {
            if ((this.MaintainGuaranteeInforOperationCompleted == null)) {
                this.MaintainGuaranteeInforOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaintainGuaranteeInforOperationCompleted);
            }
            this.InvokeAsync("MaintainGuaranteeInfor", new object[] {
                        UserID,
                        FLTID,
                        DATOP,
                        LegNo,
                        AC,
                        DepSTN,
                        ArrSTN,
                        STD,
                        ETD,
                        STA,
                        ETA,
                        ChangeReasonCode,
                        ChangeOldContent,
                        ChangeNewContent,
                        FieldType,
                        LocalOperatingTime}, this.MaintainGuaranteeInforOperationCompleted, userState);
        }
        
        private void OnMaintainGuaranteeInforOperationCompleted(object arg) {
            if ((this.MaintainGuaranteeInforCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaintainGuaranteeInforCompleted(this, new MaintainGuaranteeInforCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGuaranteeInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetGuaranteeInfor(string STN, string DATOP, string FLTID) {
            object[] results = this.Invoke("GetGuaranteeInfor", new object[] {
                        STN,
                        DATOP,
                        FLTID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetGuaranteeInforAsync(string STN, string DATOP, string FLTID) {
            this.GetGuaranteeInforAsync(STN, DATOP, FLTID, null);
        }
        
        /// <remarks/>
        public void GetGuaranteeInforAsync(string STN, string DATOP, string FLTID, object userState) {
            if ((this.GetGuaranteeInforOperationCompleted == null)) {
                this.GetGuaranteeInforOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGuaranteeInforOperationCompleted);
            }
            this.InvokeAsync("GetGuaranteeInfor", new object[] {
                        STN,
                        DATOP,
                        FLTID}, this.GetGuaranteeInforOperationCompleted, userState);
        }
        
        private void OnGetGuaranteeInforOperationCompleted(object arg) {
            if ((this.GetGuaranteeInforCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGuaranteeInforCompleted(this, new GetGuaranteeInforCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddGuaranteeRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AddGuaranteeRecord(
                    string DATOP, 
                    string FLTID, 
                    int LegNO, 
                    string AC, 
                    string FlightDate, 
                    string FlightNo, 
                    string LONG_REG, 
                    string DEPSTN, 
                    string ARRSTN, 
                    string STD, 
                    string ETD, 
                    string STA, 
                    string ETA, 
                    string Station, 
                    int GuaranteeRecordCaptionID, 
                    string GuaranteeTime, 
                    string GuaranteeContent, 
                    string UserID, 
                    string UserName, 
                    string UserDepartment) {
            object[] results = this.Invoke("AddGuaranteeRecord", new object[] {
                        DATOP,
                        FLTID,
                        LegNO,
                        AC,
                        FlightDate,
                        FlightNo,
                        LONG_REG,
                        DEPSTN,
                        ARRSTN,
                        STD,
                        ETD,
                        STA,
                        ETA,
                        Station,
                        GuaranteeRecordCaptionID,
                        GuaranteeTime,
                        GuaranteeContent,
                        UserID,
                        UserName,
                        UserDepartment});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AddGuaranteeRecordAsync(
                    string DATOP, 
                    string FLTID, 
                    int LegNO, 
                    string AC, 
                    string FlightDate, 
                    string FlightNo, 
                    string LONG_REG, 
                    string DEPSTN, 
                    string ARRSTN, 
                    string STD, 
                    string ETD, 
                    string STA, 
                    string ETA, 
                    string Station, 
                    int GuaranteeRecordCaptionID, 
                    string GuaranteeTime, 
                    string GuaranteeContent, 
                    string UserID, 
                    string UserName, 
                    string UserDepartment) {
            this.AddGuaranteeRecordAsync(DATOP, FLTID, LegNO, AC, FlightDate, FlightNo, LONG_REG, DEPSTN, ARRSTN, STD, ETD, STA, ETA, Station, GuaranteeRecordCaptionID, GuaranteeTime, GuaranteeContent, UserID, UserName, UserDepartment, null);
        }
        
        /// <remarks/>
        public void AddGuaranteeRecordAsync(
                    string DATOP, 
                    string FLTID, 
                    int LegNO, 
                    string AC, 
                    string FlightDate, 
                    string FlightNo, 
                    string LONG_REG, 
                    string DEPSTN, 
                    string ARRSTN, 
                    string STD, 
                    string ETD, 
                    string STA, 
                    string ETA, 
                    string Station, 
                    int GuaranteeRecordCaptionID, 
                    string GuaranteeTime, 
                    string GuaranteeContent, 
                    string UserID, 
                    string UserName, 
                    string UserDepartment, 
                    object userState) {
            if ((this.AddGuaranteeRecordOperationCompleted == null)) {
                this.AddGuaranteeRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGuaranteeRecordOperationCompleted);
            }
            this.InvokeAsync("AddGuaranteeRecord", new object[] {
                        DATOP,
                        FLTID,
                        LegNO,
                        AC,
                        FlightDate,
                        FlightNo,
                        LONG_REG,
                        DEPSTN,
                        ARRSTN,
                        STD,
                        ETD,
                        STA,
                        ETA,
                        Station,
                        GuaranteeRecordCaptionID,
                        GuaranteeTime,
                        GuaranteeContent,
                        UserID,
                        UserName,
                        UserDepartment}, this.AddGuaranteeRecordOperationCompleted, userState);
        }
        
        private void OnAddGuaranteeRecordOperationCompleted(object arg) {
            if ((this.AddGuaranteeRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGuaranteeRecordCompleted(this, new AddGuaranteeRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDataItemPurviewCompletedEventHandler(object sender, GetDataItemPurviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataItemPurviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataItemPurviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void MaintainGuaranteeInforCompletedEventHandler(object sender, MaintainGuaranteeInforCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaintainGuaranteeInforCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaintainGuaranteeInforCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetGuaranteeInforCompletedEventHandler(object sender, GetGuaranteeInforCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGuaranteeInforCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGuaranteeInforCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AddGuaranteeRecordCompletedEventHandler(object sender, AddGuaranteeRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGuaranteeRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGuaranteeRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591