//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSoft.FlightMonitor.AgentService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.104.16/PaxService/PaxService.asmx")]
        public string AirSoft_FlightMonitor_FlightMonitorClient_PaxService_PaxService {
            get {
                return ((string)(this["AirSoft_FlightMonitor_FlightMonitorClient_PaxService_PaxService"]));
            }
            set {
                this["AirSoft_FlightMonitor_FlightMonitorClient_PaxService_PaxService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.104.13/FocService/FocService.asmx")]
        public string AirSoft_FlightMonitor_FlightMonitorClient_FocService_FleetWatch {
            get {
                return ((string)(this["AirSoft_FlightMonitor_FlightMonitorClient_FocService_FleetWatch"]));
            }
            set {
                this["AirSoft_FlightMonitor_FlightMonitorClient_FocService_FleetWatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.104.14/FlightMonitor/Service.asmx")]
        public string AirSoft_FlightMonitor_FlightMonitorClient_FlightService_Service {
            get {
                return ((string)(this["AirSoft_FlightMonitor_FlightMonitorClient_FlightService_Service"]));
            }
            set {
                this["AirSoft_FlightMonitor_FlightMonitorClient_FlightService_Service"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.104.5/publicservice/publicservice.asmx")]
        public string AirSoft_FlightMonitor_FlightMonitorClient_PublicService_PublicService {
            get {
                return ((string)(this["AirSoft_FlightMonitor_FlightMonitorClient_PublicService_PublicService"]));
            }
            set {
                this["AirSoft_FlightMonitor_FlightMonitorClient_PublicService_PublicService"] = value;
            }
        }
    }
}
